config/routes.rb
Clockwork::Application.routes.draw do

  get 'invitation/accept'    => 'accept_invitations#accept',  :as => :accept_invitation
  put 'invitation/confirm'   => 'accept_invitations#confirm', :as => :confirm_invitation
  get 'email_change/accept'  => 'email_change#accept',        :as => :accept_email_change
  put 'email_change/confirm' => 'email_change#confirm',       :as => :confirm_email_change

  resources :notifications, only: [:index]
  get 'count_notifications'           => 'count_notifications#count',           as: 'count_notifications'
  put 'mark_notification_as_read/:id' => 'mark_notifications_as_read#one',      as: 'mark_notification_as_read'
  put 'mark_notifications_as_read'    => 'mark_notifications_as_read#multiple', as: 'mark_notifications_as_read'

  resources :accounts, except: [:show] do
    resources :reports
    resources :organizations do


      member do
        post 'add_members'
      end

      resources :plans do
        resources :attached_documents, only: [:new, :create, :destroy]
        resources :schedulings do
          resources :comments, only: [:index, :create, :destroy], controller: 'scheduling_comments'
          resource :conflicts, only: :show
        end

        # The names should correspond with the controller actions and modes of the SchedulingFilter
        scope constraints: { week: /\d{1,2}/, cwyear: /\d{4}/ } do
          get 'week/employees/:cwyear/:week' => 'schedulings#employees_in_week', :as => 'employees_in_week'
          get 'week/teams/:cwyear/:week' => 'schedulings#teams_in_week', :as => 'teams_in_week'
          get 'week/hours/:cwyear/:week' => 'schedulings#hours_in_week', :as => 'hours_in_week'
        end

        scope constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ } do
          get 'day/teams/:year/:month/:day' => 'schedulings#teams_in_day', :as => 'teams_in_day'
        end

        resource :copy_week, only: [:new, :create], controller: :copy_week
        resource :apply_plan_template, only: [:new, :create], controller: :apply_plan_template

        resources :milestones
        # TODO nest tasks under milestones, EmberData cannot do this 2012-09-11
        resources :tasks

        # TODO force ember to fetch employees from organization, not from plan
        resources :employees
      end # plans

      resources :employees do
        collection do
          get 'adopt'
          get 'search'
        end
      end
      resources :teams
      resources :team_merges, only: [:new, :create], :controller => 'team_merges'
      resources :invitations
      resources :blogs do
        resources :posts do
          resources :comments, only: [:create, :destroy], controller: 'post_comments'
        end
      end
      resources :plan_templates do
        resources :shifts
        get 'week/teams' => 'shifts#teams_in_week', :as => 'teams_in_week'
      end

      resources :qualifications

    end # organizations

  end # accounts

  resource :user, only: :show, controller: 'user'

  # For changing password when being signed in. Use named route 'change_password' to not
  # conflict with devise's named route helper 'user_password'.
  scope '/user', as: 'change' do
    get  'password'  => 'user_password#show'
    put  'password'  => 'user_password#update'
    get  'email'     => 'user_email#show'
    put  'email'     => 'user_email#update'
  end

  resource :feedback, only: [:new, :create], :controller => 'feedback'
  scope 'profile', as: 'profile' do
    resources :employees, only: [:edit, :update, :index], controller: 'profile_employees'
  end
  resource :profile, only: [:edit, :update], controller: 'profile' do
    resource :export, only: [:show, :create, :destroy]
  end

  get "dashboard" => 'welcome#dashboard', :as => 'dashboard'
  get "dashboard" => 'welcome#dashboard', :as => 'user_root'

  get "user/:user_id/employees" => 'employees#list', :as => 'list_employees'


  scope '/feeds/:email/private-:private_token', constraints: { email: %r~[^/]+~i, private_token: /[\w]{20}/i  }  do
    get 'upcoming' => 'feeds#upcoming', as: 'upcoming_feed'
  end

  put "undo" => 'undo#update', as: 'undo'


  devise_for :users, :controllers => { registrations: 'signup', sessions: 'sessions'}

  devise_scope :user do
    resource :signup, controller: 'signup', only: [:show, :create]
  end

  if Rails.env.test?
    scope 'test' do
      get 'sign_in' => 'test_acceleration#sign_in', as: 'fast_sign_in'
    end
  end

  root :to => "welcome#landing"
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
  include Volksplaner::ShortcutAttribute

  mount_uploader :avatar, AvatarUploader

  attr_accessor :organization_id,
                :force_duplicate,
                :membership_role

  validates_presence_of :first_name, :last_name
  validates_numericality_of :weekly_working_time, allow_nil: true, greater_than_or_equal_to: 0
  validates_format_of :first_name, :last_name, with: Volksplaner::HumanNameRegEx, allow_nil: true

  belongs_to :user
  belongs_to :account
  has_one    :invitation
  has_one    :owned_account, class_name: 'Account', foreign_key: 'owner_id', inverse_of: :owner
  has_many   :posts, foreign_key: :author_id
  has_many   :comments
  has_many   :schedulings
  has_many   :organizations, through: :memberships
  has_many   :memberships
  has_many   :notifications, class_name: 'Notification::Base'

  has_many   :employee_qualifications
  has_many   :qualifications, through: :employee_qualifications

  validates_presence_of :account_id
  validates_uniqueness_of :user_id, scope: :account_id, allow_nil: true
  validates_length_of :duplicates, is: 0,
    if: Proc.new { |e| e.sufficient_details_to_search_duplicates? and !e.force_duplicate? }

  before_validation :reset_duplicates
  after_save :update_or_create_membership

  def notifications_for_dashboard
    notifications.for_dashboard
  end

  def self.order_by_name
    order('last_name, first_name')
  end

  def self.default_sorting
    order_by_name.order(:id)
  end

  def owner?
    owned_account.present?
  end

  def active?
    user && user.confirmed?
  end

  def invited?
    invitation.present?
  end

  def planable?
    ! current_membership.suspended?
  end
  alias_method :planable, :planable?

  def planable=(new_val)
    current_membership.suspended = new_val.to_i != 1
  end

  def duplicates_search
    @duplicates_search ||= EmployeeSearch.duplicates_for_employee(self)
  end

  def sufficient_details_to_search_duplicates?
    duplicates_search.search?
  end

  def duplicates
    @duplicates ||= duplicates_search.results
  end

  def name
    %Q~#{first_name} #{last_name}~
  end

  def name=(new_name)
    if new_name =~ /^(\w+)\s+(\w.*)$/
      self.first_name = $1
      self.last_name = $2.strip
    end
  end

  def last_and_first_name
    %Q~#{last_name}, #{first_name}~
  end

  def membership_role
    if organization_id
      @membership_role ||
        current_membership.try(:role)
    end
  end

  def membership_for_organization(org)
    org = org.id if org.is_a?(ActiveRecord::Base)
    raise ArgumentError, "no organization/id given" if org.nil?
    memberships.where(organization_id: org).first
  end

  def current_membership
    @current_membership ||= membership_for_organization(organization_id) || memberships.build(organization_id: organization_id)
  end


  def force_duplicate?
    force_duplicate.in?(['1', 1, true])
  end

  def to_s
    %Q~<Employee #{id || 'new'} #{name.inspect} (#{weekly_working_time.presence || ''}) [#{account.try(:name)}]>~
  end

  def inspect
    to_s
  end

  private

  def update_or_create_membership
    if organization_id
      m = current_membership
      if membership_role.to_s != 'owner'
        m.role = membership_role
      end
      m.save!
    end
  end

  def reset_duplicates
    @duplicates_search = @duplicates = nil
  end
end

EmployeeDecorator

app/controllers/employees_controller.rb
class EmployeesController < BaseController
  nested_belongs_to :account, :organization
  respond_to :html, :js, :json

  before_filter :set_adoptable_employees, only: [:search, :adopt]
  before_filter :set_organization_id_on_employee, only: [:new, :create, :edit, :update]

  def create
    create! { account_organization_employees_path(current_account, current_organization) }
  end

  def update
    update! { account_organization_employees_path(current_account, current_organization) }
  end

  def search
  end

  # OPTIMIZE this is loosely coupled with OrganizationsController#add_members
  #          they should at least share a Controller, better a model, too
  def adopt
  end

  private

  def set_adoptable_employees
    search_attrs = { base: current_organization.adoptable_employees }
    search_attrs.merge!(params[:query]) if params[:query].present?
    @adoptable_employees = EmployeeSearch.new(search_attrs.symbolize_keys).fuzzy_results
  end

  def resource_params
    if [:update, :create].include?(params[:action].to_sym)
      [permitted_employee_params]
    else
      super
    end
  end

  def collection
    super.tap do |employees|
      unless @_current_org_set
        employees.each do |employee|
          set_organization_id_on_employee(employee)
        end
        @_current_org_set = true
      end
    end
  end

  # we want to use Employee#current_membership in views
  def set_organization_id_on_employee(employee = resource)
    employee.organization_id ||= current_organization.id
  end

  def permitted_employee_params
    permitted_attributes = [
      :first_name,
      :last_name,
      :weekly_working_time,
      :avatar,
      :avatar_cache,
      :organization_id,
      :account_id,
      :planable,
      :shortcut,
      :force_duplicate,
      { qualification_ids: [] }
    ]
    permitted_attributes << :membership_role if planner_or_owner?
    params.require(:employee).permit(*permitted_attributes)
  end

  def planner_or_owner?
    ['planner', 'owner'].include?(role)
  end

  def role
    if current_employee.owner?
      'owner'
    elsif current_membership.role == 'planner'
      'planner'
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def invitation_status(employee)
    if employee.active?
      t(:'employees.invitation_status.active')
    elsif employee.invited?
      t(:'employees.invitation_status.invited', invited_at: l(employee.invitation.sent_at, format: :tiny))
    else
      t(:'employees.invitation_status.not_invited_yet')
    end
  end

  def invitation_status_link(employee)
    if !employee.active? && can?(:manage, Invitation)
      if can? :manage, employee.invitation
        invitation_link(:reinvite, employee)
      else
        invitation_link(:invite, employee)
      end
    end
  end

  def invitation_link(type, employee)
    link_to ta(type),
      invitation_url(type, employee),
      class: 'button button-small', :remote => true
  end

  # TODO: let rails guess the urls by providing the persisted invitation of an employee or a new record
  def invitation_url(type, employee)
    if type == :invite
      new_account_organization_invitation_path(current_account, current_organization, invitation: { employee_id: employee.id })
    else
      edit_account_organization_invitation_path(current_account, current_organization, employee.invitation)
    end
  end

  def avatar(user, employee, version, html_classes = "")
    AvatarWidget.new(self, user, employee, version, class: html_classes).to_html
  end

  def avatar_with_caching(*a)
    @avatar_cache ||= {}
    @avatar_cache[a.map(&:to_param).join] ||= avatar_without_caching(*a)
  end

  alias_method_chain :avatar, :caching

end

app/views/employees/_adopt_employees_table.html.haml
%table#employees
  %thead
    %tr.employee
      %th= ta(:want_to_adopt)
      %th= t('activerecord.attributes.employee.full_name')
      %th.numeric= abbr_tag(t('helpers.actions.wwt_short'), t('helpers.actions.wwt_long'))
      %th= t('activerecord.attributes.employee.email')
      %th= t('employees.table.status')
      %th= t('activerecord.models.organization.others')

  %tbody
    - employees.each do |employee|
      %tr{ id: "employee_#{employee.id}" }
        %td
          - if employee.organizations.include?(current_organization)
            = t('employees.new.already_member')
          - else
            = check_box_tag 'employees[]', employee.id, false, id: "employee_#{employee.id}"
        %th
          = avatar(employee.user, employee, :tiny)
          = employee.last_and_first_name
        %td.waz.numeric= number_with_precision(employee.weekly_working_time, :precision => 2, :strip_insignificant_zeros => true)
        %td= employee.try(:user).try(:email) || employee.try(:invitation).try(:email)
        %td.status= invitation_status(employee)
        - organizations = employee.organizations
        %td= organizations.present? ? organizations.order(:name).map(&:name).join(', ') : t('none')

app/views/employees/_duplication_warning.html.haml
#duplication-warning
  - unless duplicate_employees.empty?
    %br
    %p= t('employees.new.following_duplicates_found')

    - adoptable_employees = duplicate_employees.reject { |e| e.organizations.include?(current_organization) }
    - if adoptable_employees.empty?
      %p= t('employees.new.duplicates_are_all_members')

    = form_tag([:add_members, current_account, current_organization], { id: 'add-members', class: 'add-employee' }) do |f|
      = render 'adoptable_employees_table', employees: duplicate_employees

      .actions
        %button.button-success{ disabled: adoptable_employees.empty? ? true : false}= ta(:adopt_employee)

app/views/employees/_employee.css.erb
#plan .<%= dom_id(employee) %>,
.<%= dom_id(employee) %> div {
	background-image: url(<%= employee.gravatar_url_for_css(:size => 30) %>);
}

body.statuses .<%= dom_id(employee) %> div {
	background-image: url(<%= employee.gravatar_url_for_css(:size => 30) %>);
}

app/views/employees/_employee.erb
<% content_tag_for(:li, employee, :class => "#{employee.state} resource", :'data-form-values' => employee.form_values_json) do -%>
  <%= image_tag(employee.gravatar_url(:size => 60)) %>
	<div class="actions">
		<%= link_to(t(:destroy), employee_path(employee), :class => 'delete', :method => :delete, :confirm => t(:employee_delete_confirmation)) %>
	</div>
	<h2 class="name"><%= employee.full_name %></h2>
	<p class="qualifications"><%= employee.possible_workplaces.map(&:name).join(', ') %>&nbsp;</p>
<% end -%>

app/views/employees/_other_employees_table.html.haml
%table#employees
  %thead
    %tr.employee
      %th= ta(:want_to_adopt)
      %th= t('activerecord.attributes.employee.full_name')
      %th.numeric= abbr_tag(t('helpers.actions.wwt_short'), t('helpers.actions.wwt_long'))
      %th= t('activerecord.attributes.employee.email')
      %th= t('employees.table.status')
      %th= t('activerecord.models.organization.others')

  %tbody
    - employees.each do |employee|
      %tr{ id: "employee_#{employee.id}" }
        %td= check_box_tag 'employees[]', employee.id, false, id: "employee_#{employee.id}"
        %th
          = avatar(employee.user, employee, :tiny)
          = employee.last_and_first_name
        %td.waz.numeric= number_with_precision(employee.weekly_working_time, :precision => 2, :strip_insignificant_zeros => true)
        %td= employee.try(:user).try(:email) || employee.try(:invitation).try(:email)
        %td.status= invitation_status(employee)
        - organizations = employee.organizations
        %td= organizations.present? ? organizations.order(:name).map(&:name).join(', ') : t('none')

app/views/employees/_search_form.html.haml
%p
  = t('employees.search.hint')

= form_tag([:search, current_account, current_organization, :employees],
  { id: 'search', class: 'form-vertical' }) do |f|

  .inputs
    .input
      = label_tag t('activerecord.attributes.employee.first_name')
      = text_field_tag 'first_name', nil, placeholder: t('employees.search.placeholders.first_name')
    .input
      = label_tag t('activerecord.attributes.employee.last_name')
      = text_field_tag 'last_name', nil, placeholder: t('employees.search.placeholders.last_name')
    .input
      = label_tag t('activerecord.attributes.employee.email')
      = text_field_tag 'email', nil, placeholder: t('employees.search.placeholders.email')
    .input
      = label_tag t('activerecord.attributes.employee.organization')
      = select_tag 'organization', options_from_collection_for_select(current_account.organizations, :id, :name),
      prompt: t('employees.search.placeholders.organization')

%p
  %span#search-results
  %a#clear-search.clear-search{href: '#'}= t('employees.search.clear')

app/views/employees/_search_results.html.haml
= t('employees.search.results', count: count)

app/views/employees/_table.html.haml
%table#employees
  %thead
    %tr.employee
      %th= Employee.human_attribute_name(:full_name)
      %th= Employee.human_attribute_name(:shortcut)
      %th.numeric= abbr_tag(ta(:wwt_short), ta(:wwt_long))
      %th= Employee.human_attribute_name(:email)
      %th= Employee.human_attribute_name(:planable)
      %th= Employee.human_attribute_name(:role)
      %th= t('.status')
      %th= Organization.model_name.human(count: 9001)
      %th= Employee.human_attribute_name(:qualifications)
      - if can?(:manage, Invitation)
        %th= t('.action')

  %tbody
    - records.each do |record|
      %tr{ id: "record_#{record.id}" }
        %th
          - if can?(:update, record)
            = link_to(avatar(record.user, record, :tiny),
              [:edit, current_account, current_organization, record],
              remote: true)
            = link_to(record.last_and_first_name,
              [:edit, current_account, current_organization, record],
              remote: true, :class => 'name')
          - else
            = avatar(record.user, record, :tiny)
            = record.last_and_first_name
        %td= record.shortcut
        %td.waz.numeric= number_with_precision(record.weekly_working_time,
          :precision => 2, :strip_insignificant_zeros => true)
        %td= record.try(:user).try(:email) || record.try(:invitation).try(:email)
        - record.organization_id = current_organization.id
        %td= yes_or_no_tag record.planable?
        %td= record.decorate.translated_role
        %td.status= invitation_status(record)
        - organizations = record.organizations.order(:name)
        %td
          - if organizations.present?
            - organizations.each do |org|
              %div= org.name
          - else
            = t('none')
        - qualifications = record.qualifications
        %td
          - if qualifications.present?
            - qualifications.each do |quali|
              %div= quali.name
          - else
            = t('none')
        - if can?(:manage, Invitation)
          %td.action= invitation_status_link(record)

app/views/employees/_tiny.html.haml
.employee{class: employee.planable? || 'suspended' }
  = avatar(employee.user, employee, :tiny)
  %span.name= employee.name

app/views/employees/adopt.html.haml
-title :adopt_employees

- if can? :create, Employee
  - masterhead_toolbar do
    =link_to ta(:add), [:new] + nested_resources_for(current_organization) + [:employee],
      class: 'button button-add', title: t('employees.index.add_employee')

.primary
  - unless @adoptable_employees.empty?
    = render 'search_form'
    %p= t('.not_member_yet')
    = render 'organizations/add_members_form', employees: @adoptable_employees
  - else
    %p= t('.no_adoptable_employees')

#instructions.instructions
  = tt '.instructions'

app/views/employees/create.json.erb
{
  'flash': {
    'notice': '<%= escape_javascript(flash[:notice]) %>'
  },
  'employee': <%=raw @employee.to_json %>,
  'html': {
    'append': {
      '#list': '<%= escape_javascript(render(:partial => 'employee', :object => @employee)) %>'
    },
    'replace': {
      '.employee_picture_200': '<%= escape_javascript(image_tag(@employee.gravatar_url(:size => 200), :class => 'employee_picture_200')) %>'
    }
  }
}

app/views/employees/destroy.json.erb
{
  'flash': {
    'notice': '<%= escape_javascript(flash[:notice]) %>'
  },
  'employee': <%=raw @employee.to_json %>
}

app/views/employees/index.html.haml
- title :employees

- if can? :create, Employee
  - masterhead_toolbar do
    =link_to ta(:adopt), [:adopt] + nested_resources_for(current_organization) + [:employees],
      class: 'button button-add', title: t('employees.index.adopt_employee')
    =link_to ta(:add), [:new] + nested_resources_for(current_organization) + [:employee],
      class: 'button button-add', title: t('employees.index.add_employee')

.primary
  #employees
    - unless collection.empty?
      = render 'table', records: collection
    - else
      %p= t(:'.no_employees')

#instructions.instructions
  - if can? :create, Employee
    = tt '.planner_instructions'
  - else
    = tt '.instructions'

app/views/employees/update.json.erb
{
  'flash': {
    'notice': '<%= escape_javascript(flash[:notice]) %>'
  },
  'employee': <%=raw @employee.to_json %>,
  'html': {
    'replace': {
      '#<%= dom_id(@employee) %>': '<%= escape_javascript(render(:partial => 'employee', :object => @employee)) %>',
      '.employee_picture_200': '<%= escape_javascript(image_tag(@employee.gravatar_url(:size => 200), :class => 'employee_picture_200')) %>'
    }
  }
}