config/routes.rb
Clockwork::Application.routes.draw do

  get 'invitation/accept'    => 'accept_invitations#accept',  :as => :accept_invitation
  put 'invitation/confirm'   => 'accept_invitations#confirm', :as => :confirm_invitation
  get 'email_change/accept'  => 'email_change#accept',        :as => :accept_email_change
  put 'email_change/confirm' => 'email_change#confirm',       :as => :confirm_email_change

  resources :notifications, only: [:index]
  get 'count_notifications'           => 'count_notifications#count',           as: 'count_notifications'
  put 'mark_notification_as_read/:id' => 'mark_notifications_as_read#one',      as: 'mark_notification_as_read'
  put 'mark_notifications_as_read'    => 'mark_notifications_as_read#multiple', as: 'mark_notifications_as_read'

  resources :accounts, except: [:show] do
    resources :reports
    resources :organizations do


      member do
        post 'add_members'
      end

      resources :plans do
        resources :attached_documents, only: [:new, :create, :destroy]
        resources :schedulings do
          resources :comments, only: [:index, :create, :destroy], controller: 'scheduling_comments'
          resource :conflicts, only: :show
        end

        # The names should correspond with the controller actions and modes of the SchedulingFilter
        scope constraints: { week: /\d{1,2}/, cwyear: /\d{4}/ } do
          get 'week/employees/:cwyear/:week' => 'schedulings#employees_in_week', :as => 'employees_in_week'
          get 'week/teams/:cwyear/:week' => 'schedulings#teams_in_week', :as => 'teams_in_week'
          get 'week/hours/:cwyear/:week' => 'schedulings#hours_in_week', :as => 'hours_in_week'
        end

        scope constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ } do
          get 'day/teams/:year/:month/:day' => 'schedulings#teams_in_day', :as => 'teams_in_day'
        end

        resource :copy_week, only: [:new, :create], controller: :copy_week
        resource :apply_plan_template, only: [:new, :create], controller: :apply_plan_template

        resources :milestones
        # TODO nest tasks under milestones, EmberData cannot do this 2012-09-11
        resources :tasks

        # TODO force ember to fetch employees from organization, not from plan
        resources :employees
      end # plans

      resources :employees do
        collection do
          get 'adopt'
          get 'search'
        end
      end
      resources :teams
      resources :team_merges, only: [:new, :create], :controller => 'team_merges'
      resources :invitations
      resources :blogs do
        resources :posts do
          resources :comments, only: [:create, :destroy], controller: 'post_comments'
        end
      end
      resources :plan_templates do
        resources :shifts
        get 'week/teams' => 'shifts#teams_in_week', :as => 'teams_in_week'
      end

      resources :qualifications

    end # organizations

  end # accounts

  resource :user, only: :show, controller: 'user'

  # For changing password when being signed in. Use named route 'change_password' to not
  # conflict with devise's named route helper 'user_password'.
  scope '/user', as: 'change' do
    get  'password'  => 'user_password#show'
    put  'password'  => 'user_password#update'
    get  'email'     => 'user_email#show'
    put  'email'     => 'user_email#update'
  end

  resource :feedback, only: [:new, :create], :controller => 'feedback'
  scope 'profile', as: 'profile' do
    resources :employees, only: [:edit, :update, :index], controller: 'profile_employees'
  end
  resource :profile, only: [:edit, :update], controller: 'profile' do
    resource :export, only: [:show, :create, :destroy]
  end

  get "dashboard" => 'welcome#dashboard', :as => 'dashboard'
  get "dashboard" => 'welcome#dashboard', :as => 'user_root'

  get "user/:user_id/employees" => 'employees#list', :as => 'list_employees'


  scope '/feeds/:email/private-:private_token', constraints: { email: %r~[^/]+~i, private_token: /[\w]{20}/i  }  do
    get 'upcoming' => 'feeds#upcoming', as: 'upcoming_feed'
  end

  put "undo" => 'undo#update', as: 'undo'


  devise_for :users, :controllers => { registrations: 'signup', sessions: 'sessions'}

  devise_scope :user do
    resource :signup, controller: 'signup', only: [:show, :create]
  end

  if Rails.env.test?
    scope 'test' do
      get 'sign_in' => 'test_acceleration#sign_in', as: 'fast_sign_in'
    end
  end

  root :to => "welcome#landing"
end

app/models/notification/answer_on_comment_of_employee_on_scheduling.rb
class Notification::AnswerOnCommentOfEmployeeOnScheduling < Notification::CommentOnScheduling

  def tkey
    :answer_on_comment_of_employee
  end

end

app/models/notification/answer_on_comment_of_employee_on_scheduling_of_employee.rb
class Notification::AnswerOnCommentOfEmployeeOnSchedulingOfEmployee < Notification::CommentOnScheduling

  def introductory_text_options
    super.except(:employee_name)
  end
end

app/models/notification/answer_on_comment_on_scheduling.rb
class Notification::AnswerOnCommentOnScheduling < Notification::CommentOnScheduling

  def tkey
    :answer_on_comment
  end
end

app/models/notification/answer_on_comment_on_scheduling_for_commenter.rb
class Notification::AnswerOnCommentOnSchedulingForCommenter < Notification::CommentOnScheduling

  def tkey
    :answer_on_comment_for_commenter
  end
end

app/models/notification/answer_on_comment_on_scheduling_of_employee.rb
class Notification::AnswerOnCommentOnSchedulingOfEmployee < Notification::CommentOnScheduling

  def introductory_text_options
    super.except(:employee_name)
  end
end

app/models/notification/base.rb
class Notification::Base < ActiveRecord::Base
  self.table_name = 'notifications'

  belongs_to :employee
  belongs_to :notifiable, polymorphic: true

  validates_presence_of :employee

  after_create :increase_notifications_count_on_user

  def self.default_sorting
    order('created_at desc')
  end

  def self.unread
    where(read_at: nil)
  end

  def self.for_hub
    unread.default_sorting.limit(10)
  end

  def self.for_dashboard
    default_sorting.limit(15)
  end

  def translation_key
    self.class.translation_key
  end
  alias_method :tkey, :translation_key

  def self.translation_key
    name.split('::').last.underscore.to_sym
  end

  def self.decorator_class
    NotificationDecorator
  end

  def self.mailer_class
    raise NotImplementedError, "must return a your ActionMailer::Base class used to send out mails for notifications of type #{name}"
  end

  def self.mailer_action
    raise NotImplementedError, "must return the mailer action name of your ActionMailer::Base class used to send out mails for notifications of type #{name}"
  end

  def mail_subject
    t(:mail_subject, mail_subject_options)
  end

  def mail_subject_options
    { name: acting_employee.name }
  end

  def introductory_text
    t(:introductory_text, introductory_text_options)
  end

  def introductory_text_options
    {
      name: acting_employee.name,
      date: I18n.l(post.published_at, format: :tiny)
    }
  end

  def subject
    t(:subject, subject_options)
  end

  def subject_options
    {}
  end

  def blurb
    t(:blurb, blurb_options)
  end

  def blurb_options
    {}
  end

  def acting_employee
    raise NotImplementedError, "must implement #{self.class.name}#acting_employee returning the employee who caused the reason for the notification"
  end

  def t(key, opts={})
    I18n.t(key, opts.merge(scope: "notifications.#{tkey}"))
  end

  def self.recent(num=5)
    order('updated_at DESC').limit(num)
  end

  def self.by_notifiable(notifiable)
    where(notifiable_id: notifiable.id).where(notifiable_type: notifiable.class.name)
  end

  def self.not_upcoming
    where("type != 'Notification::UpcomingScheduling'")
  end

  def self.older_than(interval)
    raise ArgumentError unless interval =~ /\A\d+ [a-z]+\z/
    where("#{table_name}.created_at < TIMESTAMP :now - INTERVAL '#{interval}'", now: Time.zone.now)
  end

  def user_locale
    locale = employee.user.try(:locale)
    locale.present? ? locale.to_sym : I18n.default_locale
  end

  def mark_as_read!
    unless read_at
      self.read_at = Time.zone.now
      save!
    end
  end

  def send_mail
    if employee.user && employee.user.receive_notification_emails
      self.class.mailer_class.public_send(self.class.mailer_action, self).deliver
      touch :sent_at
    end
  end

  private

  def increase_notifications_count_on_user
    if u = employee.user
      u.increment!(:new_notifications_count)
    end
  end
end

app/models/notification/comment.rb
class Notification::Comment < Notification::Base
  def comment
    notifiable
  end

  def acting_employee
    comment.author
  end

  def mail_subject_options
    { name: comment.author_name }
  end

  def subject
    comment.author_name
  end

  def blurb_options
    { body: truncated_body }
  end

  def truncated_body
    comment.body.truncate(30, omission: "...")
  end
end

app/models/notification/comment_on_post.rb
class Notification::CommentOnPost < Notification::Comment

  def self.mailer_class
    PostNotificationMailer
  end

  def self.mailer_action
    :new_comment
  end

  def post
    comment.commentable
  end

  def introductory_text_options
    {
      author_name: comment.author_name,
      post_title: post.title,
      date: I18n.l(comment.created_at, format: :tiny)
    }
  end

  def blurb_options
    super.merge(post_title: truncated_post_title)
  end

  def truncated_post_title
    post.title.truncate(25, omission: "...")
  end
end

app/models/notification/comment_on_post_for_commenter.rb
class Notification::CommentOnPostForCommenter < Notification::CommentOnPost
  def mail_subject_options
    { name: comment.author_name }
  end

  def introductory_text_options
    {
      author_name: comment.author_name,
      post_title: post.title,
      date: I18n.l(comment.created_at, format: :tiny)
    }
  end
end

app/models/notification/comment_on_post_of_employee.rb
class Notification::CommentOnPostOfEmployee < Notification::CommentOnPost
  def mail_subject_options
    { name: comment.author_name }
  end

  def introductory_text_options
    {
      author_name: comment.author_name,
      post_title: post.title,
      date: I18n.l(comment.created_at, format: :tiny)
    }
  end
end

app/models/notification/comment_on_scheduling.rb
class Notification::CommentOnScheduling < Notification::Comment

  def self.mailer_class
    SchedulingNotificationMailer
  end

  def self.mailer_action
    :new_comment
  end

  def introductory_text_options
    {
      author_name: comment.author_name,
      employee_name: scheduling.employee.name,
      date: I18n.l(scheduling.starts_at.to_date, format: :default_with_week_day),
      quickie: scheduling.quickie
    }
  end

  def scheduling
    comment.commentable
  end
end

app/models/notification/comment_on_scheduling_for_commenter.rb
class Notification::CommentOnSchedulingForCommenter < Notification::CommentOnScheduling

  def tkey
    :comment_for_commenter
  end
end

app/models/notification/comment_on_scheduling_of_employee.rb
class Notification::CommentOnSchedulingOfEmployee < Notification::CommentOnScheduling
end

app/models/notification/dummy.rb
# Acts as a simple Notification used in tests and features. It should show a
# non-critical message like "You did something" and should NOT be used in
# production.
class Notification::Dummy < Notification::Base
  def self.mailer_action
    'happen'
  end
  def self.mailer_class
    mock 'DummyNotificationMailer', happen: true
  end

  def acting_employee
    employee
  end

  def mail_subject
    "You did something"
  end

  def introductory_text
    "You did something awesome"
  end

  def subject
    "You did something"
  end

  def blurb
    "You did something awesome"
  end

  def notifiable_type
    'Dummy'
  end
end

app/models/notification/klass_finder.rb
class Notification::KlassFinder

  attr_reader :notifiable, :recipient

  def find(notifiable, recipient)
    @notifiable = notifiable
    @recipient  =  recipient

    case notifiable
    when ::Post
      Notification::Post
    when ::Comment
      find_klass_for_comment
    end
  end

  private

  def find_klass_for_comment
    case notifiable.commentable
    when ::Post
      find_klass_for_comment_on_post
    when ::Scheduling
      find_klass_for_comment_on_scheduling
    end
  end

  def find_klass_for_comment_on_post
    post = notifiable.commentable
    if recipient == post.author
      Notification::CommentOnPostOfEmployee
    elsif post.commenters.include? recipient
      Notification::CommentOnPostForCommenter
    else
      Notification::CommentOnPost
    end
  end

  def find_klass_for_comment_on_scheduling
    comment    = notifiable
    if comment.is_answer?
      find_klass_for_answer_on_comment_on_scheduling
    else
      find_klass_for_normal_comment_on_scheduling
    end
  end

  def find_klass_for_answer_on_comment_on_scheduling
    comment = notifiable
    scheduling = comment.commentable
    if scheduling.employee == recipient
      if comment.parent.employee == recipient
        Notification::AnswerOnCommentOfEmployeeOnSchedulingOfEmployee
      else
        Notification::AnswerOnCommentOnSchedulingOfEmployee
      end
    else
      if scheduling.commenters.include? recipient
        if comment.parent.employee == recipient
          Notification::AnswerOnCommentOfEmployeeOnScheduling
        else
          Notification::AnswerOnCommentOnSchedulingForCommenter
        end
      else
        Notification::AnswerOnCommentOnScheduling
      end
    end
  end

  def find_klass_for_normal_comment_on_scheduling
    scheduling = notifiable.commentable
    if recipient == scheduling.employee
      Notification::CommentOnSchedulingOfEmployee
    elsif scheduling.commenters.include? recipient
      Notification::CommentOnSchedulingForCommenter
    else
      Notification::CommentOnScheduling
    end
  end
end

app/models/notification/post.rb
class Notification::Post < Notification::Base

  def self.mailer_class
    PostNotificationMailer
  end

  def self.mailer_action
    :new_post
  end

  def post
    notifiable
  end

  def introductory_text_options
    {
      name: acting_employee.name,
      date: I18n.l(post.published_at, format: :tiny)
    }
  end

  def subject
    acting_employee.name
  end

  def blurb_options
    {
      title: truncated_title,
      body: truncated_body
    }
  end

  def acting_employee
    post.author
  end

  private

  def truncated_title
    post.title.truncate(25, omission: "...")
  end

  def truncated_body
    post.body.truncate(30, omission: "...")
  end
end

app/models/notification/recipients_finder.rb
class Notification::RecipientsFinder

  attr_reader :notifiable

  def find(notifiable)
    @notifiable = notifiable

    case notifiable
    when ::Post
      recipients_for_post
    when ::Comment
      recipients_for_comment
    end.select do |r|
      r.user.present? && r.user.confirmed?
    end.compact.uniq
  end

  private

  def recipients_for_post
    notifiable.organization.employees.select do |e|
      notifiable.author != e
    end
  end

  def recipients_for_comment
    case notifiable.commentable
    when ::Scheduling
      recipients_for_comment_on_scheduling
    when ::Post
      recipients_for_comment_on_post
    end
  end

  def recipients_for_comment_on_scheduling
    comment = notifiable
    scheduling = comment.commentable
    organization = scheduling.plan.organization
    (organization.planners +
     [scheduling.employee] +
     scheduling.commenters -
     [comment.employee])
  end

  def recipients_for_comment_on_post
    # An owner not being a member but the author or a commenter of the post,
    # should be notified. All other employees who are able to write posts and
    # comments are employees of the organization anyway.
    post = notifiable.commentable
    (post.organization.employees + [post.author] + post.commenters).select do |e|
      notifiable.author != e
    end
  end

end

app/models/notification/upcoming_scheduling.rb
class Notification::UpcomingScheduling < Notification::Base
  def self.mailer_class
    UpcomingSchedulingNotificationMailer
  end

  def self.mailer_action
    :upcoming_scheduling
  end

  def mail_subject_options
    {
      account: account.name,
      organization: organization.name,
      plan: plan.name
    }
  end

  def introductory_text_options
    {
      date: I18n.l(scheduling.starts_at.to_date, format: :default_with_week_day),
      quickie: scheduling.quickie
    }
  end

  def blurb_options
    {
      date: I18n.l(scheduling.starts_at.to_date),
      quickie: scheduling.quickie,
      account: account.name,
      organization: organization.name,
      plan: plan.name
    }
  end

  def acting_employee
    employee
  end

  def self.with_scheduling_ended
    joins("INNER JOIN schedulings ON schedulings.id = notifications.notifiable_id").
      where("schedulings.ends_at < '#{Time.zone.now}'")
  end

  private

  def scheduling
    notifiable
  end

  def plan
    scheduling.plan
  end

  def organization
    plan.organization
  end

  def account
    organization.account
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < InheritedResources::Base
  actions :index

  defaults resource_class: Notification::Base,
    collection_name: 'notifications',
    instance_name: 'notification'

  load_and_authorize_resource class: Notification::Base

  before_filter :reset_new_notifications_count_for_user

  respond_to :js, :html

  protected

  def begin_of_association_chain
    current_user
  end

  def end_of_association_chain
    super.default_sorting.page(params[:page]).per(30)
  end

  def reset_new_notifications_count_for_user
    current_user.new_notifications_count = 0
    current_user.save!
  end
end

app/views/notifications/_all_done.html.haml
%li.all-done
  = t(:"notifications.all_done")
  .smily
    %div= ":)"

app/views/notifications/_for_dashboard.html.haml
.module.notifications
  %header
    %h2
      = t('notifications.caption')
      %span.count= notifications.count

      -# TODO ticket #505710
      %a.side-link{style: 'display: none'} See all
  .content
    = render 'notifications/list', notifications: notifications.for_dashboard
    = link_to :show_all, notifications_path

app/views/notifications/_list.html.haml
- unless notifications.empty?
  %ul.lines
    - notifications.for_dashboard.each do |notification|
      %li{class: notification.read_at ? 'read' : 'unread' }
        = render 'notifications/subject_and_blurb', notification: notification
- else
  %p= t('notifications.no_notifications_present')

app/views/notifications/_list_for_hub.html.haml
.dropdown-menu.no-animation
  - if notifications.empty?
    %ul.notifications
      = render "notifications/all_done"
  - else
    #mark_all_as_read.global-action= link_to :mark_all_as_read,
      mark_notifications_as_read_path(notifications: notifications.map(&:id).join(',')),
      method: :put, remote: true
    %ul.notifications
      - notifications.each do |notification|
        = render "notifications/notification", notification: notification
  .global-action= link_to :show_all, notifications_path

app/views/notifications/_notification.html.haml
%li{id: dom_id(notification)}
  %actions.actions
    = link_to :mark_as_read, mark_notification_as_read_path(notification),
      method: :put, remote: true, class: 'destroy-button mark_as_read'
  = render 'notifications/subject_and_blurb', notification: notification

app/views/notifications/_notifications_list.html.haml
%ul.notifications.no-hover
  - if notifications.empty?
    = render "notifications/all_done"
  - else
    %li#mark_all_as_read= link_to :mark_all_as_read,
      mark_notifications_as_read_path(notifications: notifications.map(&:id).join(',')),
      method: :put, remote: true
  - notifications.each do |notification|
    = render "notifications/notification", notification: notification

app/views/notifications/_subject_and_blurb.html.haml
= link_to(mark_notification_as_read_path(notification), class: 'notifiable-link', method: :put) do
  = avatar notification.acting_employee.user, notification.acting_employee, :thumb, 'small'
  %subject.subject{class: 'icon-' + notification.notifiable_type.downcase}
    = notification.subject
  %blurb.blurb
    = notification.blurb

app/views/notifications/_update_count.js.erb
var current_title = $('title').text();
var count_substr_match = $.trim(current_title).match(/^\(\d+\)/);
if (count_substr_match) {
  $('title').text(current_title.replace(count_substr_match[0], ''));
}
<% if (count = current_user.new_notifications_count) > 0 %>
  $("li#notification-hub").addClass('has_new has_unread');
  $('a#notifications-count span.count').remove();
  $('a#notifications-count').append('<span class="count"><%= count %></span>')
  current_title = $('title').text();
  $('title').text('(<%= count %>)' + current_title)
<% else %>
  $("li#notification-hub").removeClass('has_new');
  $('a#notifications-count span.count').remove();
<% end %>

app/views/notifications/_update_hub.js.erb
<% unless current_user.notifications.unread.count > 0 %>
  <%= render 'notifications/update_hub_for_all_done' %>
<% end %>
<%= render 'notifications/update_count' %>
$('#notification-hub .dropdown-menu').replaceWith('<%= j render("notifications/list_for_hub", notifications: notifications) %>');

app/views/notifications/_update_hub_for_all_done.js.erb
$("li#mark_all_as_read").remove();
$("li#notification-hub").removeClass('has_unread');
$("ul.notifications").append('<%= j render("notifications/all_done") %>');

app/views/notifications/index.html.haml
- title :notifications

.notifications
  = render 'notifications/list', notifications: @notifications

= paginate @notifications

app/views/notifications/index.js.erb
<%= render 'notifications/update_hub', notifications: @notifications.for_hub %>

app/views/notifications/multiple_read.js.erb
$('li#notification-hub').replaceWith('<%= j render("application/notification_hub", notifications: current_user.notifications_for_hub) %>');

app/views/notifications/read.js.erb
$('<%= "li##{dom_id(resource)}" %>').remove();
<% notifications = current_user.unread_notifications %>
$("a#notifications-count").replaceWith('<%= j render("notifications/count", count: notifications.count) %>');
<% if notifications.empty? %>
  $("ul.notifications").append('<%= j render("notifications/all_done") %>');
<% end %>